SamTebbs33/pluto

link.ld, src/kernel/kmain.zig
This patch puts the kernel in the higher half (3GiB) with a rudimentary page directory used to map in the kernel. Currently only 4MiB are mapped in, which will need to be increased as the binary size increases and we add a heap etc. (can be done by increasing KERNEL_NUM_PAGES as needed).
The control flow is as follows: _start (sets up paging) -> start_higher_half (sets up the stack) -> kmain
The usage of Zig's `newStackCall` has been replaced with explicit assembly since it was using ~10 instructions to do what should only take 2. I think this is because it has to work out the size of the stack, so I just put a label in the linker script that represents the end of the stack and reference that from the assembly. That's a cheap little optimisation.
Closes #6
=> Feature/higher half, closes #6

build.zig, src/kernel/arch.zig, src/kernel/arch/x86/arch.zig, src/kernel/kmain.zig
This patch separates the architecture-specific and core code from each other, with the arch code moved to its own directory under `src/kernel/arch`. The architecture and core code are built to objects, then linked togetherm, and an interface is added in `src/kernel/arch.zig` which each architecture must implement.
=> Separate arch-specific and core code, closes #16

build.zig, src/kernel/arch.zig, src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/boot.zig, src/kernel/kmain.zig, src/kernel/vga.zig
This patch refactors the compilation of arch code to match the design in #27. I'd welcome advice on how to import the arch file without having to do the arch comparison in every file (perhaps with an intermediate file that does the checking that all arch-code users import?) Perhaps like this?:
```
// kmain.zig
const arch = @import(arch.zig);
fn init() void {
arch.internals.init(blah...);
}
```
```
//vga.zig
const arch = @import(arch.zig);
fn foo() void {
arch.internals.outb(blah...);
}
```
```
//arch.zig
const internals = switch (builtin.arch) {
builtin.Arch.i386 => @import("arch/x86/arch.zig");
else => unreachable;
}
```
Closes #27
=> Refactor compilation of architecture-specific code

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/gdt.zig, src/kernel/arch/x86/idt.zig, src/kernel/kmain.zig, src/kernel/log.zig, src/kernel/tty.zig
This patch adds serial logging on top of the serial interface from #41. Closes #40. Depends on #41
=> Add logging

link.ld, src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/boot.zig, src/kernel/arch/x86/constants.zig, src/kernel/arch/x86/paging.zig, src/kernel/kmain.zig, src/kernel/mem.zig
This patch adds x86 paging. It currently only supports 4MB pages since I've been having a lot of trouble with making 4KB paging work, so it can be revisited it later on. Fixes #7
=> Add x86 paging

src/kernel/arch/x86/arch.zig, test/kernel/arch_mock.zig
This patch adds `registerIntHandler(...)` to arch.zig. Closes #51
=> Add arch.registerInterruptHandler

.gitignore, build.zig, src/kernel/arch/x86/gdt.zig, src/kernel/arch/x86/idt.zig, src/kernel/arch/x86/pit.zig, src/kernel/kmain.zig, src/kernel/tty.zig, test/kernel/arch/x86/rt-test.py, test/rt-test.py
This patch adds a python script that acts as a runtime testing harness (test/rt-test.py), a new parameter to `zig build`, as well as some extra log messages for proper testing. The test harness script imports the arch-specific rt testing script from its arch directory.
It is recommended to run pkill on the qemu process after doing the testing as the process doesn't seem to be killed all the time: `zig build test -Drt-test=true; pkill qemu-system-i38`.
I would like to extend this to do more rigorous testing with more log statements once I find out how to tell the difference between an rt-test build and normal build from within the source, as adding more logging from a normal build would only pollute things.
Closes #12
=> Add runtime testing harness

README.md, azure-pipelines.yml
This patch adds continuous integration with Azure Pipelines at:
https://dev.azure.com/samueltebbs/pluto/_build?definitionId=1. This will
download zig v0.4.0 (will change to master once we upgrade our source),
build the kernel, install qemu and do runtime testing (mock testing will
also need to be done once that is up and running). Closes #13
=> Add continuous integration with Azure

azure-pipelines.yml, build.zig, src/kernel/arch/x86/arch.zig, src/kernel/kmain.zig
This patch adds the infrastructure for passing build options from build.zig to the source. At the moment the only option added is `rt_test` which will be used to run extensive runtime tests (#60). 
I added the config.zig file to hide the rather ugly build options file import from kmain.zig, much like we did with arch.zig.
Closes #59
=> Add infrastructure for build options

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/isr.zig, src/kernel/arch/x86/isr_asm.s, src/kernel/arch/x86/paging.zig, src/kernel/arch/x86/syscalls.zig, test/kernel/arch/x86/rt-test.py
This patch adds syscalls for x86. They are triggered by putting the syscall number in `eax` then trriggering interrupt `128` (The same as linux). It adds support for calling syscalls with a maximum of 5 arguments. Closes #36
=> Add x86 syscalls

build.zig
Fixes the argument to symbol-file, which is passed to gdb. Closes #75
=> Fix gdb symbol-file argument

src/kernel/arch/x86/syscalls.zig
Adds the syscall args to the syscall handler type. Closes #72
=> Add syscall args to syscall handler type

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/paging.zig, src/kernel/tty.zig
This PR adds 4KB paging support. Closes #79
=> Add 4kb paging

src/kernel/arch/x86/paging.zig, test/kernel/arch/x86/rt-test.py
Adds a runtime test to x86 paging which ensures that unmapped memory causes a page fault. If you can think of any other tests I could add please say so. Part of #60
=> Add x86 paging rt test

.github/workflows/main.yml, src/kernel/serial.zig
Adds a `zig fmt --check src` step to CI which checks that code formatting matches the chosen style. Closes #61
=> Add formatting check to CI

src/kernel/log.zig, src/kernel/serial.zig, test/rt-test.py
This patch adds runtime tests and unit tests for serial output.
It doesn't seem possible to get qemu to redirect serial data from any other port than COM1 so I can't add testing for those. The functionality is equivalent between the different ports and the port numbers are all from online documentation so I don't see there being a problem.
I also made it possible for a rt test case to specify the prefix it expects, with "[INFO] " being the default.
Closes #98
=> Add serial tests

src/kernel/kmain.zig, src/kernel/log.zig, test/rt-test.py
This patch adds log runtime tests. They will fail until #100 is merged as it needs the `prefix` argument added to `TestCase`. Closes #99
=> Add log tests

src/kernel/arch/x86/paging.zig, src/kernel/mem.zig
This patch moves `virtToPhys` from paging.zig to mem.zig as it will be used by the stacktrace code and isn't particular to any specific architecture, so should be in arch-independent code.
=> Move virtToPhys to mem.zig and add physToVirt

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/paging.zig, src/kernel/arch/x86/syscalls.zig, src/kernel/kmain.zig, src/kernel/mem.zig, test/mock/kernel/arch_mock.zig, test/rt-test.py
This patch stores the modules loaded by grub at boot time. Depends on #105
=> Load grub modules on mem init

src/kernel/arch/x86/gdt.zig, src/kernel/arch/x86/idt.zig, src/kernel/arch/x86/irq.zig, src/kernel/arch/x86/isr.zig, src/kernel/arch/x86/paging.zig, src/kernel/arch/x86/pic.zig, src/kernel/arch/x86/pit.zig, src/kernel/log.zig, src/kernel/mem.zig, src/kernel/tty.zig, src/kernel/vga.zig, test/mock/kernel/mock_framework.zig, test/mock/kernel/vga_mock.zig
This patch fixes the `T(x)` style casts in the codebase. Unnecessary casts were removed, those of the form `const/var x = T(y)` were replaced with `const/var x: T = y` and other were replaced with the new `@as` builtin. Closes #110
=> Fix T(x) style casts

.github/workflows/main.yml
This patch changes the version of zig used in CI to 0.5.0+ae0a219d1. Closes #112
=> Change CI's zig version to 0.5.0+ae0a219d1

build.zig, grub/grub.cfg, make_map.sh, src/kernel/arch/x86/boot.zig, src/kernel/arch/x86/paging.zig, src/kernel/kmain.zig, src/kernel/mem.zig, src/kernel/panic.zig, test/mock/kernel/panic_mock.zig, test/rt-test.py
This adds basic stacktrace logging when we trigger a kernel panic using a symbol table file created by readelf, which is then loaded as a module by the bootloader. Closes #44
=> Add simple stacktrace logging

src/kernel/arch/x86/boot.zig, src/kernel/arch/x86/idt.zig, src/kernel/arch/x86/interrupts.zig, src/kernel/arch/x86/irq.zig, src/kernel/arch/x86/isr.zig, test/mock/kernel/mock_framework.zig
This updates the calling convention syntax as of https://github.com/ziglang/zig/commit/5951b79af40212754071157596b8aebbe2414ffb . I will create a PR for master as well.
=> Update calling convention syntax

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/paging.zig, src/kernel/bitmap.zig, src/kernel/kmain.zig, src/kernel/mem.zig, src/kernel/pmm.zig, test/mock/kernel/arch_mock.zig, test/mock/kernel/mem_mock.zig, test/mock/kernel/paging_mock.zig, test/rt-test.py
This patch adds a physical memory manager that keeps track of which physical blocks are used. It parses the multiboot memory map for reserved memory and sets the memory used by kernel code as occupied. Closes #67
=> Add physical memory manager

.github/workflows/main.yml, build.zig, make_map.sh, makeiso.sh, src/kernel/arch/x86/gdt.zig, src/kernel/arch/x86/idt.zig, src/kernel/arch/x86/paging.zig, src/kernel/kmain.zig
Also change the build process to abstract out the Linux part of the building. This will later help with the native Windows build.
Closes #102
=> Unittest in build arch

link.ld
This patch makes sure the linker keeps the stack section, preventing it from being discarded in case there are no explicit uses. Closes #125
Depends on #127
=> Keep stack section

build.zig, src/kernel/arch/x86/gdt.zig, src/kernel/arch/x86/idt.zig, src/kernel/arch/x86/irq.zig, src/kernel/arch/x86/isr.zig, src/kernel/arch/x86/paging.zig, src/kernel/arch/x86/pic.zig, src/kernel/arch/x86/pit.zig, src/kernel/arch/x86/rtc.zig, src/kernel/arch/x86/syscalls.zig, src/kernel/bitmap.zig, src/kernel/kmain.zig, src/kernel/log.zig, src/kernel/mem.zig, src/kernel/panic.zig, src/kernel/pmm.zig, src/kernel/serial.zig, src/kernel/tty.zig, src/kernel/vga.zig, test/kernel/arch/x86/rt-test.py, test/rt-test.py
Also moving the logging to use `defer`
Closed #115
=> Update Pluto to Zig master

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/paging.zig, src/kernel/bitmap.zig, src/kernel/kmain.zig, src/kernel/mem.zig, src/kernel/pmm.zig, src/kernel/vmm.zig, test/mock/kernel/arch_mock.zig, test/mock/kernel/mem_mock.zig, test/mock/kernel/vmm_mock.zig, test/rt-test.py
This patch adds a virtual memory manager subsystem and takes the role of mapping virtual memory to physical memory from paging. The system was made architecture-independent by taking a "payload" and passing it to the mapping functions. This payload can be anything the underlying mapper (for x86 it's the paging system) needs to know when mapping (for x86 it is the page directory). Closes #68
=> Add virtual memory manager

makeiso.sh
`!/usr/bin/env bash` works on more systems than `!/bin/bash`.  I use NixOS which doesn't have `/bin/bash` and I know some BSDs also don't have `/bin/bash`.
=> use /usr/bin/env bash instead of /bin/bash

src/kernel/vmm.zig
=> Add VMM start address to allocation result

src/kernel/arch/x86/paging.zig
When a page fault occurs, will log the CPU state and the control registers.
=> Log CPU state on page fault

src/kernel/heap.zig, src/kernel/kmain.zig, test/mock/kernel/vmm_mock.zig, test/rt-test.py
This patch adds a heap allocator that in contrast to the fixed buffer allocator, allows freeing of memory. One is created by default to keep track of kernel memory and more heaps could be created to keep track of memory occupied by user programs etc.
The heap uses a [buddy allocation system](https://en.wikipedia.org/wiki/Buddy_memory_allocation) as it provides efficient allocation, freeing and little external fragmentation.
The current implementation doesn't support complex shrinking or re-allocation so I will create an issue for these that can be addressed if they actually end up being used.
Closes #8
=> Add a heap allocator

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/paging.zig, src/kernel/bitmap.zig, src/kernel/kmain.zig, src/kernel/mem.zig, src/kernel/panic.zig, src/kernel/pmm.zig, src/kernel/vmm.zig
=> Change integer types to scale up on 64 bit architectures

makeiso.sh
=> Write full symbol name to kernel symbol file

README.md, build.zig
Adds a "-Darch" option to specify the architecture to build for, which has consequences on the qemu binary used and the image creation process. Closes #154﻿
=> Add architecture option to build.zig

build.zig, src/kernel/arch/x86/link.ld
=> Move linker script

src/kernel/arch/x86/arch.zig, src/kernel/arch/x86/serial.zig, src/kernel/kmain.zig, src/kernel/log.zig, src/kernel/serial.zig, test/mock/kernel/arch_mock.zig
=> Make serial dependent on architecture

src/kernel/arch/x86/arch.zig, src/kernel/kmain.zig, src/kernel/serial.zig, test/mock/kernel/arch_mock.zig
=> Pass boot payload to serial init

src/kernel/arch/x86/boot.zig
=> Fix x86 payload

src/kernel/vfs.zig
This patch adds the virtual filesystem layer that will sit between the concrete filesystems (FAT, usb, devfs etc.) and the code that interacts with those files an directories. Much like the unix philosophy it allows anything that has a notion of reading and writing to be represented as a file.
It was designed to make interfacing with concrete filesystems trivial and smooth.
After this is merged we can start writing filesystem drivers for physical disks, a devfs and much more.
Closes #114
=> Virtual filesystem

README.md, build.zig
This will allow the user to build the OS with more fine grain, but there is a white list of supported build targets.
Closes #129
=> Use the standardTargetOptions for built targets

src/kernel/vmm.zig
=> Set the kernel VMM start address to the virtual address offset

src/kernel/heap.zig
This patch updates the heap allocator to work with the recent changes to the allocator interface. Because the new interface requires that extending memory be done with the existing allocation, rather than allowing it to be allocated elsewhere. This breaks our support for extending memory since it's non-trivial to do so with the buddy structure in use.﻿
=> Update to new allocator interface

src/kernel/vmm.zig
=> Insert the correct address into the allocations map

src/kernel/heap.zig
=> Fix heap freeing one too many blocks

src/kernel/log.zig, src/kernel/mem.zig, src/kernel/panic.zig, src/kernel/tty.zig, src/kernel/vfs.zig, test/mock/kernel/log_mock.zig, test/mock/kernel/mem_mock.zig, test/mock/kernel/mock_framework.zig, test/mock/kernel/panic_mock.zig
Updates to latest zig by replacing `var` with `anytype`.﻿
=> Zig update

src/kernel/bitmap.zig
This allows for a bitmap that doesn't need an allocator.
=> A comptime bitmap

src/kernel/heap.zig, src/kernel/kmain.zig
This patch adds a new allocator which uses a free list over a buddy system. Once this PR is done I will fully replace heap.zig with heap2.zig. Let me know if the design is unclear or if any of the code could be cleaned up since it is quite complex atm.﻿
=> Replace buddy allocator with free list allocator
